### ISSUE TITLE
Spinner while trying to load projects

### ISSUE THREAD

**Issue by IanLee1521** [doecode/client#4]
All — 

I wanted to give a heads up that I’m seeing a spinning "Loading My Projects List" when I log in to osti.gov/doecode (and end up at https://www.osti.gov/doecode/projects):

![pastedgraphic-1](https://user-images.githubusercontent.com/828452/37423649-a3b4b1dc-277b-11e8-9341-38b93ab851f9.png)

Looking at my developer tools in Safari, it appears this is caused by input-other.js (maybe):

![pastedgraphic-2](https://user-images.githubusercontent.com/828452/37423628-958a8cee-277b-11e8-9cda-dc8bf861ee67.png)

Which can be found: https://github.com/doecode/client/blob/a23cc1e0e97ad328ac741b167df7615904fe5674/web/js/input-other.js#L290

**Comment by vowelllDOE** [comment]
@SledKnight can take a look.  It's working fine in Chrome for me.

**Comment by andrewsmith4814** [comment]
@IanLee1521 , have you tried clearing your cache? That's an error that is generated when the datatables js file doesn't load, isn't loaded correctly, or isn't even included. I would suggest you try clearing your cache, and loading the page again. If you still see issues, please let us know.

**Comment by IanLee1521** [comment]
Hmm, it does appear to reload correctly, however, this is not the first time I've seen it happen..

**Comment by IanLee1521** [comment]
I also re-tried in a private browsing session and that seemed to load just fine.
