### ISSUE TITLE
Expand OSTI's Zotero translator to /doecode

### ISSUE THREAD

**Issue by katrinleinweber** [doecode/client#6]
Citations from osti.gov/energycitations & /scitech [were importable](https://github.com/zotero/translators/blob/master/OSTI%20Energy%20Citations.js) into the [reference manager Zotero](https://www.zotero.org/). On osti.gov/doecode it does not kick in, but falls back to DataCite, which unfortunately does not deliver the item type `software` or `computerProgram`:

![doe-code-zotero](https://user-images.githubusercontent.com/9948149/37766909-b4ecd3d2-2dc8-11e8-9fc2-2adfc4f9bc80.gif)

How about either expanding the existing translator, or creating a new one to simplify the software citations workflow for users? I started some notes on this on https://github.com/zotero/translators/pull/1600.

cc @mikowitz & @meberko: Guessing by the names, did one of you create that translator?

**Comment by SledKnight** [comment]
The [DOE CODE](https://www.osti.gov/doecode/) repository has been archived and is no longer actively maintained. Please visit DOE CODE for more information, or for any questions, please contact [doecoderepositories@osti.gov](mailto:doecoderepositories@osti.gov).
